[package]
name = "lunatic_ny"
version = "0.1.0"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"

[lib]
name = "lunatic_runtime"
path = "src/lib.rs"

[[bin]]
name = "lunatic"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
tokio = { version = "1.7", features = ["rt-multi-thread", "macros", "sync"] }
wasmtime = { version = "0.28", git = "https://github.com/bytecodealliance/wasmtime.git", branch = "main" }
wasmtime-wasi = { version = "0.28", git = "https://github.com/bytecodealliance/wasmtime.git", branch = "main" }

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }

[build-dependencies]
wat = "1.0"

[[bench]]
name = "benchmark"
harness = false

[workspace]
members = [
    "plugins/heap_profiler",
]