[package]
name = "lunatic-runtime"
version = "0.1.0"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"
description = "An actor platform built on WebAssembly"
license = "Apache-2.0/MIT"
readme = "Readme.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lunatic_runtime"
path = "src/lib.rs"

[[bin]]
name = "lunatic"
path = "src/main.rs"

[features]
default = ["vm-wasmer"]
vm-wasmtime = ["uptown_funk/vm-wasmtime", "wasmtime", "wasmtime-runtime"]
vm-wasmer = ["uptown_funk/vm-wasmer", "wasmer", "wasmer-vm"]

[dependencies]
async-wormhole = "0.2"
uptown_funk = { path = "./uptown_funk", features=["async"] }
wasmer = {path = "./wasmer/lib/api", optional = true}
wasmer-vm = {path = "./wasmer/lib/vm", optional = true}
wasmtime = {path = "./wasmtime/crates/wasmtime", optional = true}
wasmtime-runtime = {path = "./wasmtime/crates/runtime", optional = true}
wasi-common = "0.22.0"
getrandom = { version = "0.2.0", features = ["std"] }
walrus = "0.18"
smol = "1.2"
easy-parallel = "3"
crossbeam = "0.8"
anyhow = "1.0"
lazy_static = "1.4.0"
dashmap = "3.11"
smallvec = "1.5"
env_logger = "0.8"
log = "0.4"
rand = { version="0.8", features=["small_rng"] }

[dev-dependencies]
criterion = "0.3"
rayon = "1.5"
wat = "1.0"
wasmprinter = "0.2"
pretty_assertions = "0.6.1"

[[bench]]
name = "lunatic_benchmark"
harness = false

[[test]]
name = "normalisation_patching_test"
harness = false
