[package]
name = "uptown_funk"
version = "0.1.1"
authors = ["Bernard Kolobara <me@kolobara.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = []

[dependencies]
smallvec = "1.5"
wasmer = {path = "../wasmer/lib/api"}
wasmtime = {path = "../wasmtime/crates/wasmtime"}
uptown_funk_macro = { path = "./uptown_funk_macro" }
