[package]
name = "lunatic-process-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash-map-id = { version = "^0.1", path = "../hash-map-id" }
uuid = { version = "^0.8", features = ["v4"] }
anyhow = "^1.0"
wasmtime = "^0.34"
async-std = { version = "^1.0", features = ["attributes", "unstable"] }
lunatic-common-api = { version = "0.1", path = "../lunatic-common-api" }
lunatic-error-api = { version = "0.1", path = "../lunatic-error-api" }
lunatic-process = { version = "0.1", path = "../lunatic-process" }