[package]
name = "lunatic-distributed-api"
version = "0.9.0"
edition = "2021"
description = "A simple control server implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lunatic-common-api = { version = "0.9", path = "../lunatic-common-api" }
lunatic-process = { version = "^0.9", path = "../lunatic-process" }
lunatic-process-api = { version = "^0.9", path = "../lunatic-process-api" }
lunatic-distributed = { version = "^0.9", path = "../lunatic-distributed" }
wasmtime = "^0.36"
anyhow = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
dashmap = "5.2.0"
bincode = "^1.3"
log = "^0.4"
async_cell = "0.2.1"