on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  release:
    name: Build Lunatic
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_name: lunatic
            asset_name: lunatic-linux-amd64.tar.gz
            content_type: application/gzip
          - os: macos-latest
            target_name: lunatic
            asset_name: lunatic-macos-amd64.tar.gz
            content_type: application/gzip
          - os: windows-latest
            target_name: lunatic.exe
            asset_name: lunatic-windows-amd64.zip
            content_type: application/zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy
      - name: Build project
        run: cargo build --release
      - name: Tar release on Unix
        if: runner.os != 'Windows'
        run: |
          mv ./target/release/${{ matrix.target_name }} ${{ matrix.target_name }}
          tar czf ${{ matrix.asset_name }} README.md LICENSE-MIT LICENSE-APACHE ${{ matrix.target_name }}
      - name: Zip release on Windows
        if: runner.os == 'Windows'
        uses: papeloto/action-zip@v1
        with:
          files: README.md LICENSE-MIT LICENSE-APACHE ./target/release/${{ matrix.target_name }}
          dest: ${{ matrix.asset_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          draft: true
          files: ${{ matrix.asset_name }}
